apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: camera-trap-detection-async
spec:
  hosts:
  - "*"
  gateways:
  - ai4e-gateway
  http:
  - match:
    - uri:
        prefix: "/v1/camera-trap/detection-async"
    rewrite:
      uri: "/v1/animal_detection"
    route:
    - destination:
        host: camera-trap-detection-async.default.svc.cluster.local
        port:
          number: 1212
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-camera-trap-detection-async
spec:
  host: camera-trap-detection-async.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN