FROM ubuntu:16.04

COPY ./base-py/task_management /ai4e_api_tools/task_management
COPY ./base-r/task_management /ai4e_api_tools/task_management
COPY ./Common/task_management/distributed_api_task.py /ai4e_api_tools/task_management